export const CREATOR_NICHES = [
  "Fashion",
  "Beauty",
  "Food & Beverage",
  "Travel",
  "Lifestyle",
  "Fitness & Health",
  "Tech & Gadgets",
  "Gaming",
  "Parenting",
  "Education",
  "Finance",
  "Business",
  "Home & Decor",
  "Pets",
  "Music",
  "Photography",
  "Art & Design",
  "Sports",
  "Comedy & Entertainment",
  "Sustainability",
] as const;

export const BRAND_CATEGORIES = [
  "Fashion & Apparel",
  "Beauty & Skincare",
  "Food & Beverage",
  "Health & Wellness",
  "Tech & Electronics",
  "Home & Living",
  "Travel & Hospitality",
  "Sports & Fitness",
  "Education",
  "Finance & Fintech",
  "Automotive",
  "Entertainment",
  "Pet Products",
  "Baby & Kids",
  "Other",
] as const;

export const DEAL_STATUS_LABELS: Record<string, string> = {
  applied: "Applied",
  accepted: "Accepted",
  rejected: "Rejected",
  in_progress: "In Progress",
  completed: "Completed",
  cancelled: "Cancelled",
};
